package org.vaccineimpact.api.models.permissions

val allPermissions = listOf(
    "can-login",
    "countries.read",
    "countries.write",
    "coverage.read",
    "coverage.write",
    "diseases.write",
    "estimates.read",
    "estimates.read-unfinished",
    "estimates.review",
    "estimates.submit",
    "estimates.write",
    "modelling-groups.manage-members",
    "modelling-groups.read",
    "modelling-groups.write",
    "models.read",
    "models.write",
    "responsibilities.read",
    "responsibilities.write",
    "roles.read",
    "roles.write",
    "scenarios.read",
    "scenarios.write",
    "touchstones.finish",
    "touchstones.open",
    "touchstones.prepare",
    "touchstones.read",
    "users.read",
    "users.edit-all",
    "users.create",
    "vaccines.write"
)